# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_team.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Create(object):
    def setupUi(self, Create):
        Create.setObjectName("Create")
        Create.setWindowModality(QtCore.Qt.NonModal)
        Create.resize(662, 300)
        Create.setFocusPolicy(QtCore.Qt.StrongFocus)
        Create.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(Create)
        self.centralwidget.setObjectName("centralwidget")
        self.Team_name = QtWidgets.QLineEdit(self.centralwidget)
        self.Team_name.setEnabled(True)
        self.Team_name.setGeometry(QtCore.QRect(100, 140, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Aparajita")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.Team_name.setFont(font)
        self.Team_name.setAutoFillBackground(False)
        self.Team_name.setStyleSheet("background-color: rgb(255, 227, 200);")
        self.Team_name.setText("")
        self.Team_name.setObjectName("Team_name")
        self.save_name = QtWidgets.QPushButton(self.centralwidget)
        self.save_name.setGeometry(QtCore.QRect(250, 220, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.save_name.setFont(font)
        self.save_name.setStyleSheet("background-color: rgb(255, 147, 147);")
        self.save_name.setObjectName("save_name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 541, 91))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 149, 149);\n"
"color: rgb(0, 0, 127);\n"
"")
        self.label.setObjectName("label")
        Create.setCentralWidget(self.centralwidget)

        self.retranslateUi(Create)
        QtCore.QMetaObject.connectSlotsByName(Create)

    def retranslateUi(self, Create):
        _translate = QtCore.QCoreApplication.translate
        Create.setWindowTitle(_translate("Create", "Create"))
        self.Team_name.setPlaceholderText(_translate("Create", "enter the team name"))
        self.save_name.setText(_translate("Create", "SAVE"))
        self.label.setText(_translate("Create", "Create New Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Create = QtWidgets.QMainWindow()
    ui = Ui_Create()
    ui.setupUi(Create)
    Create.show()
    sys.exit(app.exec_())
