# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
mth=sqlite3.connect('CricketFantasyLeague.db')
cur_mth=mth.cursor()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(544, 242)
        Dialog.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_open = QtWidgets.QComboBox(self.centralwidget)
        self.cb_open.setGeometry(QtCore.QRect(160, 100, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cb_open.setFont(font)
        self.cb_open.setStyleSheet("background-color: rgb(199, 221, 255);")
        self.cb_open.setObjectName("cb_open")
        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(210, 170, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Aparajita")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.open_btn.setFont(font)
        self.open_btn.setStyleSheet("background-color: rgb(255, 156, 156);\n"
"")
        self.open_btn.setObjectName("open_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 30, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 156, 156);")
        self.label.setObjectName("label")
        Dialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        #Taking Team names
        
        teams= cur_mth.execute("SELECT DISTINCT Name FROM teams;")
        t= teams.fetchall()
        for i in t:
            self.cb_open.addItem(i[0])

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Open"))
        self.open_btn.setText(_translate("Dialog", "Open"))
        self.label.setText(_translate("Dialog", "SELECT TEAM TO OPEN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
