# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'score.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(556, 259)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(24)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.final_score = QtWidgets.QLabel(self.centralwidget)
        self.final_score.setGeometry(QtCore.QRect(200, 150, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.final_score.setFont(font)
        self.final_score.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 255);")
        self.final_score.setAlignment(QtCore.Qt.AlignCenter)
        self.final_score.setObjectName("final_score")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 30, 431, 91))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Dialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Score Dialog Box"))
        self.final_score.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Your Team Score Is : "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
